// TODO: Make sure these are the correct abbreveations for teams
export enum Teams {
  ARI = 'ARI',
  ATL = 'ATL',
  BAL = 'BAL',
  CHC = 'CHC',
  CHW = 'CHW',
  CIN = 'CIN',
  CLE = 'CLE',
  COL = 'COL',
  DET = 'DET',
  FLA = 'FLA',
  HOU = 'HOU',
  KAN = 'KAN',
  LAA = 'LAA',
  LAD = 'LAD',
  MIL = 'MIL',
  MIN = 'MIN',
  NYM = 'NYM',
  NYY = 'NYY',
  OAK = 'OAK',
  PHI = 'PHI',
  PIT = 'PIT',
  SD = 'SD',
  SF = 'SF',
  SEA = 'SEA',
  STL = 'STL',
  TB = 'TB',
  TEX = 'TEX',
  TOR = 'TOR',
  WAS = 'WAS',
}

export type Pitch = {
  pitch_type: string,
  game_date: string,
  release_speed: string,
  release_pos_x: string,
  release_pos_z: string,
  player_name: string,
  batter: string,
  pitcher: string,
  events: string,
  description: string,
  spin_dir: string,
  spin_rate_deprecated: string,
  break_angle_deprecated: string,
  break_length_deprecated: string,
  zone: string,
  des: string,
  game_type: string,
  stand: string,
  p_throws: string,
  home_team: string,
  away_team: string,
  type: string,
  hit_location: string,
  bb_type: string,
  balls: string,
  strikes: string,
  game_year: string,
  pfx_x: string,
  pfx_z: string,
  plate_x: string,
  plate_z: string,
  on_3b: string,
  on_2b: string,
  on_1b: string,
  outs_when_up: string,
  inning: string,
  inning_topbot: string,
  hc_x: string,
  hc_y: string,
  tfs_deprecated: string,
  tfs_zulu_deprecated: string,
  fielder_2: string,
  umpire: string,
  sv_id: string,
  vx0: string,
  vy0: string,
  vz0: string,
  ax: string,
  ay: string,
  az: string,
  sz_top: string,
  sz_bot: string,
  hit_distance_sc: string,
  launch_speed: string,
  launch_angle: string,
  effective_speed: string,
  release_spin_rate: string,
  release_extension: string,
  game_pk: string,
  fielder_3: string,
  fielder_4: string,
  fielder_5: string,
  fielder_6: string,
  fielder_7: string,
  fielder_8: string,
  fielder_9: string,
  release_pos_y: string,
  estimated_ba_using_speedangle: string,
  estimated_woba_using_speedangle: string,
  woba_value: string,
  woba_denom: string,
  babip_value: string,
  iso_value: string,
  launch_speed_angle: string,
  at_bat_number: string,
  pitch_number: string,
  pitch_name: string,
  home_score: string,
  away_score: string,
  bat_score: string,
  fld_score: string,
  post_away_score: string,
  post_home_score: string,
  post_bat_score: string,
  post_fld_score: string,
  if_fielding_alignment: string,
  of_fielding_alignment: string,
  spin_axis: string,
  delta_home_win_exp: string,
  delta_run_exp: string,
}
